export const CREATE_BLOG_REQUEST="CREATE_BLOG_REQUEST";
export const CREATE_BLOG_SUCCESS="CREATE_BLOG_SUCCESS";
export const CREATE_BLOG_FAIL="CREATE_BLOG_FAIL";



export const RESET_CLEAR="RESET_CLEAR";