// Action Types
export const FETCH_FRIEND_REQUESTS_REQUEST = 'FETCH_FRIEND_REQUESTS_REQUEST';
export const FETCH_FRIEND_REQUESTS_SUCCESS = 'FETCH_FRIEND_REQUESTS_SUCCESS';
export const FETCH_FRIEND_REQUESTS_FAIL = 'FETCH_FRIEND_REQUESTS_FAIL';



export const SEND_FRIEND_REQUEST_REQUEST = 'SEND_FRIEND_REQUEST_REQUEST';
export const SEND_FRIEND_REQUEST_SUCCESS = 'SEND_FRIEND_REQUEST_SUCCESS';
export const SEND_FRIEND_REQUEST_FAIL = 'SEND_FRIEND_REQUEST_FAIL';


export const RESPOND_TO_FRIEND_REQUEST_REQUEST = 'RESPOND_TO_FRIEND_REQUEST_REQUEST';
export const RESPOND_TO_FRIEND_REQUEST_SUCCESS = 'RESPOND_TO_FRIEND_REQUEST_SUCCESS';
export const RESPOND_TO_FRIEND_REQUEST_FAIL = 'RESPOND_TO_FRIEND_REQUEST_FAIL';


export const CLEAR_REQUEST="CLEAR_REQUEST";

