export const SIGNUP_REQUEST="SIGNUP_REQUEST"
export const SIGNUP_SUCCESS="SIGNUP_SUCCESS"
export const SIGNUP_FAIL="SIGNUP_FAIL"

export const LOGIN_REQUEST="LOGIN_REQUEST"
export const LOGIN_SUCCESS="LOGIN_SUCCESS"
export const LOGIN_FAIL="LOGIN_FAIL"

export const LOGIN_VALID="LOGIN_VALID"

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'; 
export const LOGOUT_FAIL = 'LOGOUT_FAIL'; 

export const PROFILE_REQUEST="PROFILE_REQUEST"
export const PROFILE_SUCCESS="PROFILE_SUCCESS"
export const PROFILE_FAIL="PROFILE_FAIL"


export const RESET_CLEAR = 'RESET_CLEAR'